### ISSUE TITLE
LED Ring Updates

### ISSUE THREAD

**Issue by vabalasu** [coleawabdy/PrototypeSoftware#1]
Can you investigate whether you need to call rgbRing.show() in each loop?

Also, could you write the code to only change the LED's that need changing? For example, if you go from 6 lights to 4, you would just turn off the top 2 instead of turning off all of them and then turning on the first 4.

Lastly, it might be nice to have "[hysteresis](https://en.wikipedia.org/wiki/Hysteresis#Control_systems)" in the light color pattern. That is, if you transition from yellow to green at, say, 800, then you would transition from green down to yellow at 790. That way, any noise in the signal will not cause the colors to flicker.

**Comment by coleawabdy** [comment]
The code in the latest commit now uses a delta calculation to determine the number of LEDs to enable, this minimizes calls to rgbRing.show().

**Comment by coleawabdy** [comment]
The latest commit implements hysteresis, it also makes the color dependent on the direct value of the pot rather then the number of LEDs enabled.
